update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -90,7 +90,7 @@ jobs:
         USE_LATEST_TAG=false            # true / false
         USE_TAG=''                      # 2.1.1
         USE_BRANCH='bugfix-2.1.x'       # bugfix-2.1.x
-        BOARD='mega2560'                # mega2560 / 
+        BOARD='mega2560ext'                # mega2560 / 
 
         # git repository
         git clone https://github.com/MarlinFirmware/Marlin.git 
@@ -157,6 +157,60 @@ jobs:
             printf "\e[1;35mCompiling Marlin firmware..\e[0m\n\n"
             platformio run -d Marlin/
 
+            ls -la
+
             success=$?
+
+            
+
+            # # Override firmware file extension
+            # if [ "$FW_EXTENSION" ]; then
+            #   printf "\n\e[01;36mOverride Detected\e[0m\n"
+            #   printf "Setting firmware file extension to:\e[01;33m $FW_EXTENSION\e[0m\n"
+            # else
+            #   FW_EXTENSION=bin
+            # fi
+
+
+            # if [[ ${success} -eq 0 ]]; then
+            #   OUTPUT_DIR=/home/platformio/build/$BOARD
+            #   mkdir -p $OUTPUT_DIR
+
+            #   printf "\nCopying compiled firmware to output folder..\n"
+            #   cd /home/platformio/Marlin/.pio/build/$BOARD
+
+            #   if [ $(find . -name "*.${FW_EXTENSION}") ];
+            #   then
+            #     FIRMWARE_NAME=$(find . -name "*.${FW_EXTENSION}" -type f -exec basename {} .${FW_EXTENSION} ';')
+            #     md5sum $FIRMWARE_NAME.$FW_EXTENSION > $OUTPUT_DIR/$FIRMWARE_NAME.md5
+            #     cp $FIRMWARE_NAME.$FW_EXTENSION $OUTPUT_DIR
+
+            #     printf "\nValidating firmware checksum.."
+            #     if md5sum -c $OUTPUT_DIR/$FIRMWARE_NAME.md5;
+            #     then
+            #       printf "\e[0mMD5 Checksum Validation: \e[1;32mSucceeded\n"
+            #       echo ""
+            #       echo "  (\.   \      ,/)"
+            #       echo "   \(   |\     )/    Yer done!"
+            #       echo "   //\  | \   /\\"
+            #       echo "  (/ /\_#oo#_/\ \)   Happy 3D-Printing!"
+            #       echo "   \/\  ####  /\/"
+            #       echo "        '##'"
+            #       echo ""
+            #     else
+            #       printf "\e[0mMD5 Checksum Validation: \e[1;31mFailed\n"
+            #       printf "\n\e[1;31mBuild failed! \e[0mCheck the output above for errors\n"
+            #       exit 1
+            #     fi
+            #   else
+            #       printf "\e[0mMD5 Checksum Validation: \e[1;31mFirmware file with $FW_EXTENSION file extension not found!\n"
+            #       printf "\n\e[1;31mBuild failed! \e[0mCheck the output above for errors\n"
+            #       exit 1
+            #   fi
+            # else
+            #   printf "\n\e[1;31mBuild failed! \e[0mCheck the output above for errors\n"
+            #   exit 1
+            # fi
+
 
         done
